package ping

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PingOKCode is the HTTP code returned for type PingOK
const PingOKCode int = 200

/*PingOK successful operation

swagger:response pingOK
*/
type PingOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPingOK creates PingOK with default headers values
func NewPingOK() *PingOK {
	return &PingOK{}
}

// WithPayload adds the payload to the ping o k response
func (o *PingOK) WithPayload(payload string) *PingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ping o k response
func (o *PingOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// PingBadRequestCode is the HTTP code returned for type PingBadRequest
const PingBadRequestCode int = 400

/*PingBadRequest Invalid status value

swagger:response pingBadRequest
*/
type PingBadRequest struct {
}

// NewPingBadRequest creates PingBadRequest with default headers values
func NewPingBadRequest() *PingBadRequest {
	return &PingBadRequest{}
}

// WriteResponse to the client
func (o *PingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// PingForbiddenCode is the HTTP code returned for type PingForbidden
const PingForbiddenCode int = 403

/*PingForbidden Access denied

swagger:response pingForbidden
*/
type PingForbidden struct {
}

// NewPingForbidden creates PingForbidden with default headers values
func NewPingForbidden() *PingForbidden {
	return &PingForbidden{}
}

// WriteResponse to the client
func (o *PingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// PingInternalServerErrorCode is the HTTP code returned for type PingInternalServerError
const PingInternalServerErrorCode int = 500

/*PingInternalServerError Operation error

swagger:response pingInternalServerError
*/
type PingInternalServerError struct {
}

// NewPingInternalServerError creates PingInternalServerError with default headers values
func NewPingInternalServerError() *PingInternalServerError {
	return &PingInternalServerError{}
}

// WriteResponse to the client
func (o *PingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
